FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app/server

# Copy package.json and package-lock.json (if available)
COPY server/package*.json ./

# Install app dependencies
RUN npm install

# Copy app source
COPY server/ .

# Build the TypeScript app
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD [ "npm", "start" ]
