"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var applicationController_1 = require("../controllers/applicationController");
var router = (0, express_1.Router)();
router.post("/", applicationController_1.createApplication);
router.get("/", applicationController_1.getAllApplications);
router.get("/:id", applicationController_1.getApplicationById);
router.put("/:id", applicationController_1.updateApplication);
router.delete("/:id", applicationController_1.deleteApplication);
exports.default = router;
