"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var internshipProgramController_1 = require("../controllers/internshipProgramController");
var router = (0, express_1.Router)();
router.post("/", internshipProgramController_1.createInternshipProgram);
router.get("/", internshipProgramController_1.getAllInternshipPrograms);
router.get("/:id", internshipProgramController_1.getInternshipProgramById);
router.put("/:id", internshipProgramController_1.updateInternshipProgram);
router.delete("/:id", internshipProgramController_1.deleteInternshipProgram);
exports.default = router;
