"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var mouController_1 = require("../controllers/mouController");
var router = (0, express_1.Router)();
router.post("/", mouController_1.createMOU);
router.get("/", mouController_1.getAllMOUs);
router.get("/:id", mouController_1.getMOUById);
router.put("/:id", mouController_1.updateMOU);
router.delete("/:id", mouController_1.deleteMOU);
exports.default = router;
